### ISSUE TITLE
Sensor not detecting new items in Inbox

### ISSUE THREAD

**Issue by ngesnetworks** [StackStorm-Exchange/stackstorm-msexchange#11]
The issue is similar to #8 but I'm seeing the same issue with the polling sensor generating the `INFO [-] Found 0 items`, yet I can run `st2 run msexchange.search_items folder=Inbox` and have it finding new items in the Inbox, the sensor `msexchange.ItemSensor` is not finding/triggering on any new items.

```2018-07-31 12:40:54,025 DEBUG [-] Using Python: 2.7.12 (/opt/stackstorm/st2/bin/python)
2018-07-31 12:40:54,026 DEBUG [-] Using config files: /etc/st2/st2.conf
2018-07-31 12:40:54,026 DEBUG [-] Using logging config: /etc/st2/logging.sensorcontainer.conf
2018-07-31 12:40:54,030 INFO [-] Connecting to database "st2" @ "127.0.0.1:27017" as user `"stackstorm".
2018-07-31 12:40:54,035 INFO [-] Successfully connected to database "st2" @ "127.0.0.1:27017" as user "stackstorm".
2018-07-31 12:40:54,276 INFO [-] Running in single sensor mode, using a single sensor partitioner...
2018-07-31 12:40:54,280 INFO [-] Setting up container to run 1 sensors.
2018-07-31 12:40:54,281 INFO [-]        Sensors list - [u'msexchange.ItemSensor'].
2018-07-31 12:40:54,281 INFO [-] (PID:7460) SensorContainer started.
2018-07-31 12:40:54,283 INFO [-] Running sensor msexchange.ItemSensor
2018-07-31 12:40:54,289 AUDIT [-] Access granted to "sensors_container" with the token set to expire at "2018-08-01T17:40:54.286474Z". (username='sensors_container',token_expiration='2018-08-01T17:40:54.286474Z')
2018-07-31 12:40:54,289 WARNING [-] "auth.api_url" configuration option is not configured
2018-07-31 12:40:54,344 INFO [-] Connected to amqp://guest:**@127.0.0.1:5672//
2018-07-31 12:40:54,370 INFO [-] Sensor msexchange.ItemSensor started
2018-07-31 12:40:55,766 INFO [-] Found config for sensor "ItemSensor"
2018-07-31 12:40:55,794 INFO [-] Watcher started
2018-07-31 12:40:55,795 INFO [-] Running sensor initialization code
2018-07-31 12:40:55,818 INFO [-] Connected to amqp://guest:**@127.0.0.1:5672//
2018-07-31 12:40:56,310 INFO [-] Running sensor in passive mode
2018-07-31 12:40:56,312 WARNING [-] "auth.api_url" configuration option is not configured
2018-07-31 12:40:56,319 AUDIT [-] Access granted to "sensor_service" with the token set to expire at "2018-08-01T17:40:56.316871Z". (username='sensor_service',token_expiration='2018-08-01T17:40:56.316871Z')
2018-07-31 12:40:56,449 INFO [-] Found 0 items
2018-07-31 12:41:01,622 INFO [-] Found 0 items
```
I also validated by using `st2 trigger-instance list` and found that there was no trigger generated.

The ST2 version is `st2 2.8.1, on Python 2.7.12`

**Comment by LindsayHill** [comment]
`msexchange.search_items` only filters by subject if one is given. It does not filter by timestamp or read/unread status.

The sensor code does do filtering by timestamp and 'read' status.

What happens if you do an interactive Python session, use msexchangelib to connect to that account, and search for items, *with* and *without* timestamp & read/unread filtering?

**Comment by LindsayHill** [comment]
I wonder if the time stamp code is wrong. Should be easy to test out.

**Comment by LindsayHill** [comment]
@ngesnetworks is your system time zone the same as the time zone in your `/opt/stackstorm/configs/msexchange.yaml` file?

**Comment by ngesnetworks** [comment]
@LindsayHill For the `msexchange.yaml` file I originally had `American/Chicago`, but I just changed it to `UTC` and registered the config. After doing so I ran `sudo /opt/stackstorm/st2/bin/st2sensorcontainer --config-file=/etc/st2/st2.conf --sensor-ref=msexchange.ItemSensor` and the sensor worked. But I am now seeing the following error message.
```2018-08-01 08:55:29,379 WARNING [-] Sensor "ItemSensor" run method raised an exception: argument must be 9-item sequence, not EWSDateTime.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py", line 250, in run
    self._sensor_instance.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2reactor/sensor/base.py", line 105, in run
    self.poll()
  File "/opt/stackstorm/packs/msexchange/sensors/item_sensor.py", line 55, in poll
    self._set_last_date(payload['datetime_received'])
  File "/opt/stackstorm/packs/msexchange/sensors/item_sensor.py", line 81, in _set_last_date
    self._last_date = time.strftime('%Y-%m-%dT%H:%M:%S', last_date)
TypeError: argument must be 9-item sequence, not EWSDateTime
```
I also tested out just simply removing the Timezone from the yaml file and it showed the same issue with the EWSDateTime. 

```2018-08-01 09:12:15,171 ERROR [-]   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py", line 382, in <module>
2018-08-01 09:12:15,172 ERROR [-]
2018-08-01 09:12:15,172 ERROR [-] obj.run()
2018-08-01 09:12:15,173 ERROR [-]   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py", line 256, in run
2018-08-01 09:12:15,173 ERROR [-]
2018-08-01 09:12:15,174 ERROR [-] raise Exception(msg)
2018-08-01 09:12:15,174 ERROR [-] Exception
2018-08-01 09:12:15,174 ERROR [-] :
2018-08-01 09:12:15,175 ERROR [-] Sensor "ItemSensor" run method raised an exception: argument must be 9-item sequence, not EWSDateTime.
2018-08-01 09:12:15,175 ERROR [-]
2018-08-01 09:12:15,176 INFO [-] Stopping trigger watcher
```

**Comment by LindsayHill** [comment]
What happens if you set your time zone to be the same as your server time zone?

**Comment by ngesnetworks** [comment]
My timezone and the server timezone are the same.

**Comment by ngesnetworks** [comment]
I used the Teaser from the library to get connected up. [https://github.com/ecederstrand/exchangelib#teaser](url)

```from exchangelib import Credentials, Account

credentials = Credentials('john@example.com', 'topsecret')
account = Account('john@example.com', credentials=credentials, autodiscover=True)

for item in account.inbox.all().order_by('-datetime_received')[:100]:
    print(item.subject, item.sender, item.datetime_received)
```
I was able to pull in the following.

```No handlers could be found for logger "exchangelib.account"
('testing', Mailbox(name='****************', email_address='*************', routing_type='SMTP', mailbox_type='Mailbox', item_id=None), EWSDateTime(2018, 8, 1, 18, 13, 10, tzinfo=<UTC>))
```

I used a simple `print(account.inbox.unread_count)` and was able to get the correct read/unread count.
Then I used `for item in account.inbox.all(): print(item.datetime_received)` and was able to get the times associated with it. The times that are pulled through are UTC (since I'm using datetime) I see `18:37:16+00:00`, which is as expected. When I use it with the original teaser code I see `EWSDateTime(2018, 8, 1, 18, 13, 10, tzinfo=<UTC>)`.

**Comment by LindsayHill** [comment]
So what's probably needed is to update these pieces:
```python
self._set_last_date(payload['datetime_received'])
...
 def _set_last_date(self, last_date):
        self._last_date = time.strftime('%Y-%m-%dT%H:%M:%S', last_date)
        self._sensor_service.set_value(name=self._store_key,
                                       value=self._last_date)
```

And make sure that this bit `time.strftime('%Y-%m-%dT%H:%M:%S', last_date)` is getting `last_date` in the format it expects.

**Comment by minsis** [comment]
This is still an issue for first time sensor start up.

As the sensor comes online the stored date is `None` which then defaults to `datetime.now()`. This never gets stored so the sensor is never able to pick anything up.

Stored date is None -> start_date is set to datetime.now() - any email previous to now() is never detected.

Probably need to add set last date as well so that we can get the triggers moving forward.
https://github.com/StackStorm-Exchange/stackstorm-msexchange/blob/577ce37490d224089a6c4dd7642400808477827a/sensors/item_sensor.py#L47-L49

**Comment by minsis** [comment]
I'm happy to submit a PR on this if we can have a discussion on the direction to go.

**Comment by amanda11** [comment]
> Maybe the bigger question here is do we actually need to use a stored datetime? Since the sensor filters out all non-read items and then marks any new items as read it wont see those items again on the next execution.

I don't use this pack, but looking at the logic I would agree for the most part the date check could be removed, and it would resolve this issue and simplify logic.

There is one use case that I think would differ:
1. We get in an email
2. Sensor picks it up (and currently we note the time)
3. If we at a later point mark that email as unread....
Then currently that email wouldn't get picked up again, but if we change the logic to remove the date checking then the email would get sent in a second time.

The imap filter in the email pack, however just uses your simpler logic which is to just return the unread rather than keep a tab on the last updated.

Would be interesting to hear back from anyone actively using this pack, to see if this change in logic would have any detrimental affect on them.

As the alternative would be that if its not set, then don't filter by date after done the unread, so only do that if we have a stored_date set.

**Comment by minsis** [comment]
Currently the sensor will only pick up unread emails after x datetime. So the only way the same email might be picked up is if the sensor executes again before the previous one finishes and I'm not even sure if that's possible with st2?

https://github.com/StackStorm-Exchange/stackstorm-msexchange/blob/577ce37490d224089a6c4dd7642400808477827a/sensors/item_sensor.py#L51

This pack also does not do any sorting, and I'm not sure what the default sorting method is. So really the last stored datetime value is going to be the last item in the list depending on how its sorted it could be asc or desc and we'd end up storing the wrong datetime anyways.

Personally as of today I've cloned this repo and removed the datetime store all together and it works fine. It checks the folder for any unread emails and then marks them read. Just in my experience with other commercial software the way I've modified this pack without the datetime store is how they also work - checking for unread emails, not after a certain time period. 

Here you can see that one check found one item and the next found zero. The email that it marked unread is still in that same mailbox.
```
2021-11-02 14:45:24,377 140248160129096 INFO item_sensor [-] Found 1 items
2021-11-02 14:46:27,145 140248160129096 INFO item_sensor [-] Found 0 items
```

IMHO the way I see it we have two options:
1. Remove datetime all together (which is what I'm in favor of), or
2. Add ` self._set_last_date(stored_date)` after line 48 in order to store an initial value on first time use. This way at the very least there will be a 1m window that emails can be picked up by the sensor.

In the end I think there's just too many issues to hinge it on the datetime. In the grand scheme of unreliable email a 1m window isn't really enough. Email delays, emails that are scheduled can actually have a datetime stamp of the template and not the actual email sent, etc.

**Comment by amanda11** [comment]
What I meant was if we remove the date time check, then in the scenario mentioned - this would cause us to get the message a 2nd time if the user marks it as unread.

however I would have expected in most scenarios we would be monitoring accounts where someone wasn’t going to do that.

And as you said delays on timing would mess it up - and I would feel they would be more likely to happen then read emails on an account being monitored being marked as unread.

I am also in favour of removing the date time check.

**Comment by jamesdreid** [comment]
We use this pack internally for a number of different things (we currently have an open PR on this pack with some additional enhancement added to the Sensor to hopefully can be merged at some point), but I would have to look at the code again to see if there would be any impact to removing the datetime check.  My guess is there will not be any issue (aside from the possibility of duplicate triggers if emails are reset manually to unread) with that but I will need to confirm.

**Comment by minsis** [comment]
@amanda11 So looking at #17 a lot of the datetime stuff is fixed there and made optional. However, it removes the `is_read` flag which I think shouldn't be the case or at the very least made optional. What's nice about it is it allows you to do relative datetime searches which makes good sense.

Anyways, this PR is 5 months old and seems like it was abandoned and not merged for some reason. Although the request for  a fix wasn't made until beginning of last month. Can we move forward with this PR - I can work on any fixes if they're not meeting requirements.

**Comment by minsis** [comment]
> @amanda11 So looking at #17 a lot of the datetime stuff is fixed there and made optional. However, it removes the `is_read` flag which I think shouldn't be the case or at the very least made optional. What's nice about it is it allows you to do relative datetime searches which makes good sense.
> 
> Anyways, this PR is 5 months old and seems like it was abandoned and not merged for some reason. Although the request for a fix wasn't made until beginning of last month. Can we move forward with this PR - I can work on any fixes if they're not meeting requirements.

Actually I'm mistaken it doesn't change the sensor, just the actions when searching for items. Still, the PR is a pretty good  update to this package. With the dateutil included with that PR making similar changes to the  sensor would be trivial.

**Comment by amanda11** [comment]
@jamesdreid Did you get chance to see if removing the dateutil logic from the sensor would cause any problems?
@minsis Are you thinking now of making the sensor so that the check on pulling only from last date optional? Or still going for the remove the date logic?
I'm not sure this fix is reliant on #17 getting merged?

Thanks for the review comments on #17, once those are addressed I think we can move forward on that PR getting merged.

**Comment by minsis** [comment]
Sorry I got confused; I was thinking dateutil was dateparser library. So I guess my plan is back to removing it which doesn't rely on #17. But, #17 does make changes to the item_sensory.py so there would probably be merge conflicts if I make changes  now.

**Comment by jamesdreid** [comment]
After discussing internally, the general consensus was there would be no impact.  We should be fine to go ahead with the dateutil logic from the sensor, but I would prefer it was done AFTER #17 was merged (or fully rejected with reason) as it was submitted by an associate of mine and is used internally for extracting attachments from emails processed by the sensor and is an integral component to some of our automation workflows. If #17 is not merged, we will just continue to use our forked version and the dateutil logic will make no difference.

**Comment by minsis** [comment]
So what are next steps to getting #17 merged?

**Comment by amanda11** [comment]
@minsis #17 merged now.

**Comment by minsis** [comment]
Hi @amanda11,

Sorry for the gross delay here, been trying to keep my head above water! Anyways, PR #21 fixes the issue of datetime check for the item sensor.
